import theme from "@/src/theme";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { SettingsProvider } from "./SettingsContext";

const ebGaramond = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const geistMono = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        className={`${ebGaramond.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider theme={theme}>
          <NextIntlClientProvider messages={messages}>
            <AppRouterCacheProvider>
              <SettingsProvider>{children}</SettingsProvider>
            </AppRouterCacheProvider>
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
